### ISSUE TITLE
flutter-gallery has been moved to gallery repo. Please make the following changes in the documentation.

### ISSUE THREAD

**Issue by Dantusaikamal** [devoncarew/pesto#11]
In the readme.md, it is given that this demo has been extracted from the larger [flutter_gallery](https://github.com/flutter/flutter/tree/master/examples/flutter_gallery) example.

Update the link and redirect it to the [gallery_repo](https://github.com/flutter/gallery)

**Comment by devoncarew** [comment]
archiving this repo
